config/routes.rb
Static::Application.routes.draw do
  
  devise_for :users
  
  root to: "home#index"
  
  get "assessments/:assessment_id", to: "assessment#edit", as: :edit_assessment
  put "assessments/:assessment_id", to: "assessment#update"
  
  get "assessments/:assessment_id/users/:user_id", to: "assessment#show", as: :user_assessment
  
  get "manager_reviews", to: "manager_reviews#index", as: :manager_reviews
  post "manager_reviews", to: "manager_reviews#create"
  get "manager_reviews/new", to: "manager_reviews#new", as: :new_manager_review
  get "manager_reviews/:id", to: "manager_reviews#show", as: :manager_review
  
  get "manager_reviewer/:token", to: "manager_reviewer#new", as: :review_manager
  post "manager_reviewer/:token", to: "manager_reviewer#create"
  
  # get "assessments/:assessment_id/users/:user_id/form", to: "scores#edit", as: :assessment_form
  # put "assessments/:assessment_id/users/:user_id/form", to: "scores#update"
  
  # Tester Bar
  post "tester_bar/:action", controller: "tester_bar" if Rails.env.development?
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
    @assessment = Assessment.current
  end
  
end

app/views/home/index.html.erb
<% if @assessment.assessors.member?(current_user) %>
<% if show_group_assessment? and (show_group_assessment_before_complete? or @assessment.completed?)  %>
  <ul id="users" class="cards">
    <% @users.each do |user| %>
      <li class="user card">
        <%= avatar_for(user, size: 160) %>
        <span class="user-name">
          <%= link_to user.name, user_assessment_path(@assessment, user) %>
        </span>
        
        <dl class="stat-key">
          <dt class="stat-level-group"></dt><dd>Group assessment <%= completion(of: user) %></dd>
          <dt class="stat-level-personal"></dt><dd>My assessment <%= completion(of: user, by: current_user) %></dd>
        </dl>
        
        <%= render "users/stats", stats: @assessment.results(of: user, by: current_user) %>
      </li>
    <% end %>
  </ul>
<% elsif @assessment.completed?(by: current_user) %>
  <ul id="users" class="cards">
    <% @users.each do |user| %>
      <li class="user card">
        <%= avatar_for(user, size: 160) %>
        <span class="user-name">
          <%= link_to user.name, user_assessment_path(@assessment, user) %>
        </span>
        
        <dl class="stat-key">
          <dt class="stat-level-group"></dt><dd>Group assessment</dd>
          <dt class="stat-level-personal"></dt><dd>My assessment <%= completion(of: user, by: current_user) %></dd>
        </dl>
        
        <%= render "users/stats", stats: @assessment.results(of: user, only_by: current_user) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <%= link_to "Begin Assessment", edit_assessment_path(@assessment), class: "btn btn-success btn-large" %>
<% end %>
<% end %>