config/routes.rb
Static::Application.routes.draw do
  
  devise_for :users
  
  root to: "home#index"
  
  get "assessments/:assessment_id", to: "assessment#edit", as: :edit_assessment
  put "assessments/:assessment_id", to: "assessment#update"
  
  get "assessments/:assessment_id/users/:user_id", to: "assessment#show", as: :user_assessment
  
  get "manager_reviews", to: "manager_reviews#index", as: :manager_reviews
  post "manager_reviews", to: "manager_reviews#create"
  get "manager_reviews/new", to: "manager_reviews#new", as: :new_manager_review
  get "manager_reviews/:id", to: "manager_reviews#show", as: :manager_review
  
  get "manager_reviewer/:token", to: "manager_reviewer#new", as: :review_manager
  post "manager_reviewer/:token", to: "manager_reviewer#create"
  
  # get "assessments/:assessment_id/users/:user_id/form", to: "scores#edit", as: :assessment_form
  # put "assessments/:assessment_id/users/:user_id/form", to: "scores#update"
  
  # Tester Bar
  post "tester_bar/:action", controller: "tester_bar" if Rails.env.development?
  
end

app/models/manager_review/section.rb
class ManagerReview < ActiveRecord::Base
  class Section < Struct.new(:predicate, :questions)
  end
end

app/controllers/manager_reviews_controller.rb
class ManagerReviewsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:show]
  
  def index
    @manager_reviews = ManagerReview.for(current_user)
  end
  
  def new
    @review = ManagerReview.new(manager: current_user)
  end
  
  def create
    @review = ManagerReview.new(new_review_params)
    if @review.save
      redirect_to manager_reviews_path, notice: "Invitations sent!"
    else
      render :new
    end
  end
  
  def show
    @review = ManagerReview.find params[:id]
    @manager = @review.manager
  end
  
private
  
  def new_review_params
    params.require(:manager_review).permit(:reviewer_emails).merge(manager: current_user)
  end
  
end

app/views/manager_reviews/_results.html.erb
<% @review.sections.each do |section| %>
  <div class="review-section">
    <h4><%= @manager.first_name %> <%= section.predicate %></h4>
    
    <table class="likert-fields">
      <%= likert_table_header %>
      <tbody>
        <% section.questions.each do |question| %>
          <tr class="likert-field">
            <th class="likert-field-question"><%= question %></th>
            <td class="likert-field-responses" colspan="5">
              <div class="guide" style="margin-left: 20%"></div>
              <div class="guide" style="margin-left: 40%"></div>
              <div class="guide" style="margin-left: 60%"></div>
              <div class="guide" style="margin-left: 80%"></div>
              <% @review.grouped_results_for(question).each do |value, count| %>
                <div class="value" style="margin-left: <%= offset(value) %>%; font-size: <%= count %>em;"></div>
              <% end %>
              <div class="value average-value" style="margin-left: <%= offset(@review.average_result_for(question)) %>%"></div>
            </td>
            <td class="likert-field-response">&nbsp;</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/manager_reviews/index.html.erb
<h2>Manager Reviews</h2>

<ul class="manager-reviews">
  <% @manager_reviews.each do |review| %>
    <li class="manager-review">
      <%= link_to manager_review_path(review) do %>
        <%= format_date(review.date) %>
        (<%= review.reviewers.map(&:email_address).join(", ") %>)
      <% end %>
      
      <% if review.completed? %>
        &mdash; Complete
      <% else %>
        &mdash; Incomplete
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "New Review", new_manager_review_path, class: "btn btn-primary" %>

app/views/manager_reviews/new.html.erb
<h2>New Manager Review</h2>

<%= form_for @review do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-block">
      <ul>
        <% @review.errors.full_messages.each do |error| %>
          <li class="validation-error"><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :reviewer_emails, "List the Email Addresses of your Employees, one per line"%>
  <%= f.text_area :reviewer_emails, rows: 6 %>
  
  <p>
    <%= f.submit "Send Invitations", class: "btn btn-primary" %>
  </p>
<% end %>

app/views/manager_reviews/show.html.erb
<h2>Review on <%= format_date @review.date %></h2>

<p><%= @review.reviewers.completed.count %> of <%= pluralize @review.reviewers.count, "reviewers" %> have completed the review.</p>

<%= render "manager_reviews/results" if @review.completed? %>