config/routes.rb
Static::Application.routes.draw do
  
  devise_for :users
  
  root to: "home#index"
  
  get "assessments/:assessment_id", to: "assessment#edit", as: :edit_assessment
  put "assessments/:assessment_id", to: "assessment#update"
  
  get "assessments/:assessment_id/users/:user_id", to: "assessment#show", as: :user_assessment
  
  get "manager_reviews", to: "manager_reviews#index", as: :manager_reviews
  post "manager_reviews", to: "manager_reviews#create"
  get "manager_reviews/new", to: "manager_reviews#new", as: :new_manager_review
  get "manager_reviews/:id", to: "manager_reviews#show", as: :manager_review
  
  get "manager_reviewer/:token", to: "manager_reviewer#new", as: :review_manager
  post "manager_reviewer/:token", to: "manager_reviewer#create"
  
  # get "assessments/:assessment_id/users/:user_id/form", to: "scores#edit", as: :assessment_form
  # put "assessments/:assessment_id/users/:user_id/form", to: "scores#update"
  
  # Tester Bar
  post "tester_bar/:action", controller: "tester_bar" if Rails.env.development?
  
end

app/views/layouts/_tester_bar.html.erb
<div style="position: fixed; left: 0; right: 0; bottom: 0; height: 42px; line-height: 36px; background: black; padding-left: 4px;">
  <%= form_tag "/tester_bar/login_as" %>
    <%= select_tag "email", options_for_select(User.all.map { |u| ["#{u.name}", u.email] }, current_user.try(:email)), :style => "margin-bottom: 0" %>
    <button class="btn btn-primary" type="submit" title="Log in as any user">Login</button>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Static" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Static</a>
          <div class="container-fluid">
            <ul class="nav">
              <% if can?(:create, ManagerReview) %>
                <li><%= link_to "Manager Reviews", manager_reviews_path %></li>
              <% end %>
              <% if current_user %>
                <li><%= link_to "Sign Out", "/users/sign_out"  %></li>
                <li><a><%= current_user.name %></a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div><!-- /container -->

    <%= render partial: "layouts/tester_bar" if Rails.env.development? -%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Static" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Static</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div><!-- /container -->

    <%= render partial: "layouts/tester_bar" if Rails.env.development? -%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>